---
# See: https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths
# See: https://github.com/adrienverge/yamllint/issues/360
ignore: |
  edax-reversi

extends: default

# See: https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false # for GitHub Actions
  comments:
    min-spaces-from-content: 1
    # quoted-strings: # See: https://stackoverflow.com/a/69850618/10928938
