include: package:pedantic_sensuikan1973/analysis_options.yaml

analyzer:
  exclude:
    # array workaround は ffigen で生成したコードをパクってきてるので ignore
    # TODO: ffigen 導入して、binding 周りを yaml に追いやりたい
    # See: https://github.com/sensuikan1973/libedax4dart/pull/10
    - lib/src/bindings/structs/move_list.dart
