name: dartfmt

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', '.github/workflows/dartfmt.yaml']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/dartfmt.yaml']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:dev
    steps:
    - uses: actions/checkout@v2
    - name: dart format
      run: dart format ./ -l 120 --set-exit-if-changed
