name: Integration Test

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', '.github/workflows/integration_test.yaml', 'scripts/build_libedax.sh', '.libedax-version']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/integration_test.yaml', 'scripts/build_libedax.sh', '.libedax-version']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false # I want results from all OSes even if one fails.
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        dart_channel: [beta]
        include:
          - os: ubuntu-20.04
            libedax_build_command: make libbuild ARCH=x64 COMP=gcc OS=linux
            libedax_bin: libedax.so
          - os: windows-2019
            libedax_build_command: make libbuild ARCH=x64 COMP=gcc OS=windows
            libedax_bin: libedax-x64.dll
          - os: macos-11
            libedax_build_command: make libbuild ARCH=x64-modern COMP=gcc OS=osx
            libedax_bin: libedax.dylib
    steps:
    - uses: actions/checkout@v2

    - uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.dart_channel }}

    - name: build libedax
      env:
        dst: '.'
        libedax_build_command: ${{ matrix.libedax_build_command }}
      run: sh scripts/build_libedax.sh

    - name: output build info
      shell: bash
      run: .github/scripts/output_build_info.sh . gcc && cat env.txt

    # # DEBUG
    # - name: setup tmate session for debug
    #   uses: mxschmitt/action-tmate@v3

    - name: install dependencies
      run: pub get
    - name: test
      run: pub run test . --coverage=coverage
    - name: coverage
      run: pub run coverage:format_coverage --lcov --packages=.packages --in coverage --out lcov.info
    - uses: codecov/codecov-action@v2.0.3
      with:
        file: lcov.info

    - name: run example
      run: |-
        cd example && pub get && cd ..
        dart example/example.dart
