name: Shell Script CI

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '.github/workflows/shell_script_ci.yaml'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s bash # See: https://github.com/koalaman/shellcheck/issues/809
