name: unit_test

on:
  pull_request:
    paths: ['**.dart', 'pubspec.*', '.github/workflows/unit_test.yaml', 'scripts/build_libedax.sh']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/unit_test.yaml', 'scripts/build_libedax.sh']

jobs:
  build:
    env:
      libedax_bin: libedax.dylib
      cache_ver: 1
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - uses: cedx/setup-dart@v2
      with:
        architecture: x64
        release-channel: beta

    - name: cache libedax assets for test
      id: cache-libedax-assets
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.libedax_bin }}
          data
        key: ${{ env.cache_ver }}-${{ runner.os }}-libedax-assets-${{ hashFiles('scripts/build_libedax.sh') }}

    - name: build libedax
      if: steps.cache-libedax-assets.outputs.cache-hit != 'true'
      env:
        dst: '.'
        libedax_build_command: make libbuild ARCH=x64-modern COMP=gcc OS=osx
      run: |-
        sh scripts/build_libedax.sh
        mv bin/${{ env.libedax_bin }} ./${{ env.libedax_bin }} # for test

    - name: install dependencies
      run: pub get
    - name: test
      run: pub run test .
